### PR TITLE
Fix to double counting reads that have sup aln

### PR DESCRIPTION
**Pull request by BenjaminSchwessinger**
Fixed the issue of double counting reads in bam files with supplementary alignment. See issue #17.

### CODE REVIEW

**Comment by wdecoster** [comment]
Hi Benjamin,

Thanks! But I'm not yet sure if I agree 100%. Please let me know what you think about my reasoning behind keeping supplementary alignments up until now:
From my understanding, supplementary alignments are real, but not directly linear with the primary alignment, e.g. with chimeric alignments, structural variants or library prep artifacts. So, therefore, a supplementary alignment is not a duplicate or multi-mapper, but a unique part of the sequenced read mapping non-linear to the arbitrarily picked primary alignment. As such I'm not sure if it's fine to just ignore them?

Cheers,
Wouter

**Comment by BenjaminSchwessinger** [comment]
I agree with your interpretation of supplemental aln and it is good to include them. It all depends a bit how you handle them downstream.

I think the problem is that some "read.query_name" will be counted twice right now. And you dataframe has more entries than unique mapped reads. This gets a bit confusing downstream I think.

E.g.
Right now in the "process_bam" function you print the following:
"Nanoget: bam {} contains {} primary alignments.".format(
        bam, datadf["lengths"].size))

Not sure this is correct as handled right now.

Else if you go to nanomath.py the following happens.
class Stats(object):
    self.number_of_reads = len(df)
    self.number_of_bases = np.sum(df["lengths"])
.....

Here you take the length of the dataframe of for the number of reads and such. This gets all a bit confusing. 

I stop digging here and I hope you can see were I am coming from with double counting of reads and bases. You might get around this with some set() and dropduplicates() and such.

Great stuff overall. Thanks for putting it out there and making it really discoverable.

**Comment by wdecoster** [comment]
Yes, right, that's confusing at least and not entirely correct. I'll think about this some more in the next days. It seems things would be better if I would not mention "number of reads" but "number of alignments", perhaps, but that's perhaps also not very clear.

**Comment by wdecoster** [comment]
Hi Benjamin,

I'm sorry to not follow up on this for so long, and I thank you for taking the time to dive into the code to make these changes. I have decided that I want to make this extension optional and have pushed code to take care of that. Nanoget has now a `keep_supp` kwarg for the bam/cram processing, which is used by NanoPlot (which now has a `--no_supplementary`) flag on the commandline.

Cheers,
Wouter

**Pull request closed without merging**
